
    - name: copying mogodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
        remote_src: true
    
    - name: installing mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present
      
    - name: enabling service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
    
    - name: changing port
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: restarting
      ansible.builtin.service:
        name: mongod
        state: restarted
  