[mongodb]
mongodb.daws23.space

[catalogue]
catalogue.daws23.space

[redis]
redis.daws23.space

[cart]
cart.daws23.space
[user]
user.daws23.space
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321